In [4]:
from google.colab import drive
drive.mount('/content/drive')
ROOT_PATH="/content/drive/MyDrive/"

Mounted at /content/drive


In [10]:
import os.path
os.path.isfile("/content/drive/MyDrive/20201666.pdf")

True

In [1]:
import nltk
nltk.download('gutenberg')
nltk.download('punkt')

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Unzipping corpora/gutenberg.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [2]:
from nltk.corpus import gutenberg
import numpy as np
from nltk.tokenize import sent_tokenize, word_tokenize
import random

In [3]:
for fileid in gutenberg.fileids():
  num_words = len(gutenberg.words(fileid))
  print(num_words, fileid)

192427 austen-emma.txt
98171 austen-persuasion.txt
141576 austen-sense.txt
1010654 bible-kjv.txt
8354 blake-poems.txt
55563 bryant-stories.txt
18963 burgess-busterbrown.txt
34110 carroll-alice.txt
96996 chesterton-ball.txt
86063 chesterton-brown.txt
69213 chesterton-thursday.txt
210663 edgeworth-parents.txt
260819 melville-moby_dick.txt
96825 milton-paradise.txt
25833 shakespeare-caesar.txt
37360 shakespeare-hamlet.txt
23140 shakespeare-macbeth.txt
154883 whitman-leaves.txt


In [6]:
# Print the file IDs in the Gutenberg dataset
print("File IDs in Gutenberg dataset:")
print(gutenberg.fileids())

# Print example text from the first file
example_id = gutenberg.fileids()[4]
print(f"\nExample text from file ID {example_id}:")
print(gutenberg.raw(example_id)[:1000])  # Display first 1000 characters


File IDs in Gutenberg dataset:
['austen-emma.txt', 'austen-persuasion.txt', 'austen-sense.txt', 'bible-kjv.txt', 'blake-poems.txt', 'bryant-stories.txt', 'burgess-busterbrown.txt', 'carroll-alice.txt', 'chesterton-ball.txt', 'chesterton-brown.txt', 'chesterton-thursday.txt', 'edgeworth-parents.txt', 'melville-moby_dick.txt', 'milton-paradise.txt', 'shakespeare-caesar.txt', 'shakespeare-hamlet.txt', 'shakespeare-macbeth.txt', 'whitman-leaves.txt']

Example text from file ID blake-poems.txt:
[Poems by William Blake 1789]

 
SONGS OF INNOCENCE AND OF EXPERIENCE
and THE BOOK of THEL


 SONGS OF INNOCENCE
 
 
 INTRODUCTION
 
 Piping down the valleys wild,
   Piping songs of pleasant glee,
 On a cloud I saw a child,
   And he laughing said to me:
 
 "Pipe a song about a Lamb!"
   So I piped with merry cheer.
 "Piper, pipe that song again;"
   So I piped: he wept to hear.
 
 "Drop thy pipe, thy happy pipe;
   Sing thy songs of happy cheer:!"
 So I sang the same again,
   While he wept with jo

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [13]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [3]:
# Define the label_tokens function
def label_tokens(my_text):
    tokenized_words = my_text.split()  # Use word_tokenize for better tokenization
    labels = []

    # Label each token with the next token in the sentence
    for i in range(0, len(tokenized_words) - 1):
        labels.append(tokenized_words[i + 1])
    labels.append('null')

    labeled_words = list(zip(tokenized_words, labels))
    return labeled_words

example_id = gutenberg.fileids()[4]
text = gutenberg.raw(example_id)

sentences = sent_tokenize(text)

# print(sentences)

# Process each sentence with label_tokens and combine the results
labeled_text = []

for sentence in sentences:
    labeled_sentence = label_tokens(sentence)
    labeled_text.extend(labeled_sentence)

print(labeled_text[:100])
# for labeled_token in labeled_text:
#     print(labeled_token)

[('[Poems', 'by'), ('by', 'William'), ('William', 'Blake'), ('Blake', '1789]'), ('1789]', 'SONGS'), ('SONGS', 'OF'), ('OF', 'INNOCENCE'), ('INNOCENCE', 'AND'), ('AND', 'OF'), ('OF', 'EXPERIENCE'), ('EXPERIENCE', 'and'), ('and', 'THE'), ('THE', 'BOOK'), ('BOOK', 'of'), ('of', 'THEL'), ('THEL', 'SONGS'), ('SONGS', 'OF'), ('OF', 'INNOCENCE'), ('INNOCENCE', 'INTRODUCTION'), ('INTRODUCTION', 'Piping'), ('Piping', 'down'), ('down', 'the'), ('the', 'valleys'), ('valleys', 'wild,'), ('wild,', 'Piping'), ('Piping', 'songs'), ('songs', 'of'), ('of', 'pleasant'), ('pleasant', 'glee,'), ('glee,', 'On'), ('On', 'a'), ('a', 'cloud'), ('cloud', 'I'), ('I', 'saw'), ('saw', 'a'), ('a', 'child,'), ('child,', 'And'), ('And', 'he'), ('he', 'laughing'), ('laughing', 'said'), ('said', 'to'), ('to', 'me:'), ('me:', '"Pipe'), ('"Pipe', 'a'), ('a', 'song'), ('song', 'about'), ('about', 'a'), ('a', 'Lamb!"'), ('Lamb!"', 'null'), ('So', 'I'), ('I', 'piped'), ('piped', 'with'), ('with', 'merry'), ('merry', 'cheer

In [4]:
word_list = []
for words, _ in labeled_text:
  word_list.append(words)
print(word_list)

label_list = []
for _, labels in labeled_text:
  label_list.append(labels)
print(label_list)

['[Poems', 'by', 'William', 'Blake', '1789]', 'SONGS', 'OF', 'INNOCENCE', 'AND', 'OF', 'EXPERIENCE', 'and', 'THE', 'BOOK', 'of', 'THEL', 'SONGS', 'OF', 'INNOCENCE', 'INTRODUCTION', 'Piping', 'down', 'the', 'valleys', 'wild,', 'Piping', 'songs', 'of', 'pleasant', 'glee,', 'On', 'a', 'cloud', 'I', 'saw', 'a', 'child,', 'And', 'he', 'laughing', 'said', 'to', 'me:', '"Pipe', 'a', 'song', 'about', 'a', 'Lamb!"', 'So', 'I', 'piped', 'with', 'merry', 'cheer.', '"Piper,', 'pipe', 'that', 'song', 'again;"', 'So', 'I', 'piped:', 'he', 'wept', 'to', 'hear.', '"Drop', 'thy', 'pipe,', 'thy', 'happy', 'pipe;', 'Sing', 'thy', 'songs', 'of', 'happy', 'cheer:!"', 'So', 'I', 'sang', 'the', 'same', 'again,', 'While', 'he', 'wept', 'with', 'joy', 'to', 'hear.', '"Piper,', 'sit', 'thee', 'down', 'and', 'write', 'In', 'a', 'book,', 'that', 'all', 'may', 'read."', 'So', 'he', "vanish'd", 'from', 'my', 'sight;', 'And', 'I', "pluck'd", 'a', 'hollow', 'reed,', 'And', 'I', 'made', 'a', 'rural', 'pen,', 'And', 'I

In [5]:
word_pairs = [(word, idx) for idx, word in enumerate(word_list)]
vocab_map = dict(word_pairs)

print(vocab_map.get("[Poems"))

0


In [6]:
import numpy as np

def one_hot_vector(word):
    vector = np.zeros(len(vocab_map))
    index = vocab_map.get(word)
    if index != None:
      vector[index] = 1
    return vector
print(one_hot_vector("[Poems"))
print(one_hot_vector("Mansi"))

[1. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]


In [7]:
def get_vector_list(label_words_list):
  vector_list = []
  for word in range(0, len(label_words_list)):
    vector = one_hot_vector(word)
    vector_list.append(vector)
  return vector_list

words_vector = get_vector_list(word_list)
labels_vector = get_vector_list(label_list)

print(words_vector)
print(labels_vector)

[array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 

In [8]:
import torch
from torch.utils.data import TensorDataset, DataLoader, random_split

words_tensor = torch.tensor(np.array(words_vector)).float()
labels_tensor = torch.tensor(np.array(labels_vector)).float()
print(f"size(words_tensor):{words_tensor.size()}")
print(f"size(labels_tensor):{words_tensor.size()}")


dataset = TensorDataset(words_tensor, labels_tensor)
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

trainset, valset = random_split(dataset, [train_size, val_size])

print(trainset)
print(valset)

trainloader = DataLoader(trainset, batch_size=64, shuffle=True)
valloader = DataLoader(valset, batch_size=64, shuffle=True)

size(words_tensor):torch.Size([6846, 2396])
size(labels_tensor):torch.Size([6846, 2396])


In [9]:
import torch
from torch import nn, optim

In [10]:
class SimpleNN(nn.Module):
    def __init__(self, input_size, output_size):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, 128)
        self.fc2 = nn.Linear(128, output_size)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Model, loss, and optimizer
input_size = len(words_vector[0])
output_size = len(words_vector[0])
print(f"input_size:{input_size}")
print(f"output_size:{output_size}")
model = SimpleNN(input_size, output_size)
criterion = nn.MSELoss()  # Mean Squared Error loss function for regression
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training example
words, labels = next(iter(trainloader))
print(f"Words shape: {words.shape}")
print(f"Labels shape: {labels.shape}")

# Forward pass
# outputs = model(words)  # Model outputs
# loss = criterion(outputs, labels)  # Calculate the MSE loss
# print(f"Loss: {loss.item()}")

input_size:2396
output_size:2396
Words shape: torch.Size([64, 2396])
Labels shape: torch.Size([64, 2396])


In [11]:
def one_hot_ce_loss(outputs, targets):
    criterion = nn.CrossEntropyLoss()
    _, labels = torch.max(targets, dim=1)
    return criterion(outputs, labels)

example_targets = torch.tensor([[0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 1, 0]], dtype=torch.int32)
example_outputs = torch.rand(size=(4, 3), dtype=torch.float32)
example_loss = one_hot_ce_loss(example_outputs, example_targets)
print(example_loss)

tensor(1.0401)


In [24]:
num_epochs = 10

# Training loop
for epoch in range(num_epochs):
    model.train()  # Set the model to training mode
    running_loss = 0.0

    for batch_words, batch_labels in trainloader:
        # Zero the parameter gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(batch_words)
        print(outputs.shape)

        print(f"batch labels: {batch_labels.shape}")

        # Compute loss
        #loss = criterion(outputs, batch_labels)
        loss = one_hot_ce_loss(outputs, batch_labels)

        # Backward pass and optimization
        loss.backward()
        optimizer.step()

        # Accumulate loss
        running_loss += loss.item() * batch_words.size(0)

    # Print average loss for this epoch
    epoch_loss = running_loss / len(trainloader.dataset)
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {epoch_loss:.4f}")
    # print(f"Epoch {epoch+1}/{num_epochs}, Loss: {running_loss:.4f}")

    # Validation step (optional, for checking model performance on validation set)
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for batch_words, batch_labels in valloader:
            outputs = model(batch_words)
            loss = criterion(outputs, batch_labels)
            val_loss += loss.item() * batch_words.size(0)
    val_loss /= len(valloader.dataset)
    print(f"Validation Loss: {val_loss:.4f}")

torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: torch.Size([64, 2396])
torch.Size([64, 2396])
batch labels: tor

KeyboardInterrupt: 

In [100]:
import torch

def predict(model, input_tensor):
    """
    Predicts the output for given input using the trained model.

    Args:
    - model (nn.Module): The trained neural network model.
    - input_tensor (torch.Tensor): The input tensor for which to make predictions.

    Returns:
    - torch.Tensor: The predicted outputs.
    """
    # Set the model to evaluation mode
    model.eval()

    # Ensure input_tensor is of correct shape
    with torch.no_grad():  # No need to compute gradients for inference
        outputs = model(words_tensor)

    return outputs

# Example usage
# Assuming words_vector contains your input data
input_data = words_tensor[:5]  # Take the first 5 samples as an example
predictions = predict(model, input_data)
print(predictions)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 7.4506e-09, 0.0000e+00,
         3.7253e-09],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 7.4506e-09, 0.0000e+00,
         3.7253e-09]])


In [99]:
print(words_tensor[:5])

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
